name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        docker: [{image: ubuntu:24.04, tag: cpu}, {image: nvidia/cuda:12.8.0-cudnn-devel-ubuntu24.04, tag: cuda}]
        exclude:
          - os: ubuntu-24.04-arm
            docker: {image: nvidia/cuda:12.8.0-cudnn-devel-ubuntu24.04, tag: cuda}
    

    runs-on: ${{ matrix.os }}
    
    steps:
    - 
      uses: actions/checkout@v4
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        build-args: |
          IMAGE=${{ matrix.docker.image }}
        tags: ghcr.io/ucsd-e4e/fishsense:${{ matrix.docker.tag }}
        push: true
