name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        docker: 
          - {image: ubuntu, image_tag: 24.04, push_tag: cpu,}
          - {image: nvidia/cuda, image_tag: 12.6.3-cudnn-devel-ubuntu24.04, push_tag: cuda}
        exclude:
          - os: ubuntu-24.04-arm
            docker: {image: nvidia/cuda, image_tag: 12.6.3-cudnn-devel-ubuntu24.04, push_tag: cuda}
    

    runs-on: ${{ matrix.os }}
    
    steps:
    - 
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Generate Dockerfile
      run: |
        python -m fishsense_docker --image ${{ matrix.docker.image }}:${{ matrix.docker.image_tag }} --output Dockerfile
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        tags: ghcr.io/ucsd-e4e/fishsense:${{ matrix.docker.push_tag }}
        push: true
